"""Pydantic schemas registry."""

from app.schemas.common import (
    APIResponse,
    PaginatedResponse,
    HealthResponse,
    MessageResponse,
    ErrorDetail,
    ValidationErrorResponse,
)
from app.schemas.auth import (
    UserRegisterRequest,
    UserLoginRequest,
    UserResponse,
    TokenResponse,
    RefreshTokenRequest,
    GoogleAuthRequest,
    ForgotPasswordRequest,
    ResetPasswordRequest,
    ChangePasswordRequest,
    VerifyEmailRequest,
    VerifyPhoneRequest,
    UserProfileUpdateRequest,
    UserSettingsResponse,
    UserSettingsUpdateRequest,
    VerificationChangeRequest,
)
from app.schemas.creator import (
    PortfolioItemSchema,
    CreatorPackageSchema,
    CreatorProfileResponse,
    CreatorProfileUpdateRequest,
    CollaborationCreateRequest,
    CollaborationResponse,
    CollaborationStatusUpdateRequest,
)
from app.schemas.service import (
    ServiceResponse,
    ServiceListResponse,
    ServiceDetailResponse,
    ReviewCreateRequest,
    ReviewResponse,
    SearchSuggestionItem,
    SearchSuggestionsResponse,
    SearchResponse,
    TimeSlotItem,
    DayAvailabilityItem,
    ServiceAvailabilityResponse,
    ServiceCreatePayload,
    ServiceUpdatePayload,
)
from app.schemas.booking import (
    BookingCreateRequest,
    BookingResponse,
    BookingListResponse,
    ProviderBookingResponse,
    ProviderBookingListResponse,
    ProviderBookingStatusUpdateRequest,
)
from app.schemas.payment import (
    PaymentOrderCreateRequest,
    PaymentOrderResponse,
    PaymentVerifyRequest,
    PaymentVerificationResponse,
)
from app.schemas.earnings import (
    EarningsDataPoint,
    ProviderEarningsResponse,
)
from app.schemas.payout import (
    PayoutItemResponse,
    ProviderPayoutSummaryResponse,
    PayoutCreateRequest,
)
from app.schemas.admin import (
    AdminOverviewResponse,
    AdminUserItemResponse,
    AdminPartnerVerificationRequest,
    AdminServiceStatusRequest,
    AdminPayoutStatusRequest,
    AdminSupportTicketItem,
    AdminPlatformSettingsResponse,
)
from app.schemas.notification import (
    NotificationResponse,
    NotificationListResponse,
    NotificationMarkReadRequest,
)
from app.schemas.message import (
    MessageResponse as ChatMessageResponse,
    ConversationResponse,
    ConversationDetailResponse,
    MessageSendRequest,
)
from app.schemas.support import (
    TicketReplyItem,
    SupportTicketCreateRequest,
    SupportTicketReplyRequest,
    SupportTicketResponse,
    SupportTicketListResponse,
)
from app.schemas.refund import (
    RefundResponse,
    RefundListResponse,
)
from app.schemas.saved_service import (
    SavedServiceResponse,
    SavedServiceStatusResponse,
    SavedServiceListResponse,
)

__all__ = [
    "APIResponse",
    "PaginatedResponse",
    "HealthResponse",
    "MessageResponse",
    "ErrorDetail",
    "ValidationErrorResponse",
    "UserRegisterRequest",
    "UserLoginRequest",
    "UserResponse",
    "TokenResponse",
    "RefreshTokenRequest",
    "GoogleAuthRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "ChangePasswordRequest",
    "VerifyEmailRequest",
    "VerifyPhoneRequest",
    "UserProfileUpdateRequest",
    "UserSettingsResponse",
    "UserSettingsUpdateRequest",
    "VerificationChangeRequest",
    "PortfolioItemSchema",
    "CreatorPackageSchema",
    "CreatorProfileResponse",
    "CreatorProfileUpdateRequest",
    "CollaborationCreateRequest",
    "CollaborationResponse",
    "CollaborationStatusUpdateRequest",
    "ServiceResponse",
    "ServiceListResponse",
    "ServiceDetailResponse",
    "ReviewCreateRequest",
    "ReviewResponse",
    "SearchSuggestionItem",
    "SearchSuggestionsResponse",
    "SearchResponse",
    "TimeSlotItem",
    "DayAvailabilityItem",
    "ServiceAvailabilityResponse",
    "ServiceCreatePayload",
    "ServiceUpdatePayload",
    "BookingCreateRequest",
    "BookingResponse",
    "BookingListResponse",
    "ProviderBookingResponse",
    "ProviderBookingListResponse",
    "ProviderBookingStatusUpdateRequest",
    "PaymentOrderCreateRequest",
    "PaymentOrderResponse",
    "PaymentVerifyRequest",
    "PaymentVerificationResponse",
    "EarningsDataPoint",
    "ProviderEarningsResponse",
    "PayoutItemResponse",
    "ProviderPayoutSummaryResponse",
    "PayoutCreateRequest",
    "AdminOverviewResponse",
    "AdminUserItemResponse",
    "AdminPartnerVerificationRequest",
    "AdminServiceStatusRequest",
    "AdminPayoutStatusRequest",
    "AdminSupportTicketItem",
    "AdminPlatformSettingsResponse",
    "NotificationResponse",
    "NotificationListResponse",
    "NotificationMarkReadRequest",
    "ChatMessageResponse",
    "ConversationResponse",
    "ConversationDetailResponse",
    "MessageSendRequest",
    "TicketReplyItem",
    "SupportTicketCreateRequest",
    "SupportTicketReplyRequest",
    "SupportTicketResponse",
    "SupportTicketListResponse",
    "RefundResponse",
    "RefundListResponse",
    "SavedServiceResponse",
    "SavedServiceStatusResponse",
    "SavedServiceListResponse",
]
