/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AITripPlannerRouteImport } from './routes/AI-trip-planner'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as AdminActivityApprovalRouteImport } from './routes/admin/activity-approval'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminApprovalsRouteImport } from './routes/admin/approvals'
import { Route as AdminBlogsRouteImport } from './routes/admin/blogs'
import { Route as AdminFarmApprovalRouteImport } from './routes/admin/farm-approval'
import { Route as AdminFraudRouteImport } from './routes/admin/fraud'
import { Route as AdminHelpRouteImport } from './routes/admin/help'
import { Route as AdminHomeRouteImport } from './routes/admin/home'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminVerifiedUsersRouteImport } from './routes/admin/verified-users'
import { Route as AdminVerifyRouteImport } from './routes/admin/verify'
import { Route as AuthChangePasswordRouteImport } from './routes/auth/change-password'
import { Route as AuthChange_passwordRouteImport } from './routes/auth/change_password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogIdRouteImport } from './routes/blog/$id'
import { Route as CreatorAnalyticsRouteImport } from './routes/creator/analytics'
import { Route as CreatorBoardRouteImport } from './routes/creator/board'
import { Route as CreatorBookingsRouteImport } from './routes/creator/bookings'
import { Route as CreatorBrandDealsRouteImport } from './routes/creator/brand-deals'
import { Route as CreatorCollaborationsRouteImport } from './routes/creator/collaborations'
import { Route as CreatorFollowersRouteImport } from './routes/creator/followers'
import { Route as CreatorHelpRouteImport } from './routes/creator/help'
import { Route as CreatorHomeRouteImport } from './routes/creator/home'
import { Route as CreatorInstagramRouteImport } from './routes/creator/instagram'
import { Route as CreatorMessagesRouteImport } from './routes/creator/messages'
import { Route as CreatorNotificationsRouteImport } from './routes/creator/notifications'
import { Route as CreatorPaymentsRouteImport } from './routes/creator/payments'
import { Route as CreatorPortfolioRouteImport } from './routes/creator/portfolio'
import { Route as CreatorProfileRouteImport } from './routes/creator/profile'
import { Route as CreatorReportsRouteImport } from './routes/creator/reports'
import { Route as CreatorRevenueRouteImport } from './routes/creator/revenue'
import { Route as CreatorSavedFarmsRouteImport } from './routes/creator/saved-farms'
import { Route as CreatorSettingsRouteImport } from './routes/creator/settings'
import { Route as CreatorSocialRouteImport } from './routes/creator/social'
import { Route as CreatorYoutubeRouteImport } from './routes/creator/youtube'
import { Route as CreatorcardSlugRouteImport } from './routes/creatorcard/$slug'
import { Route as FarmerActivitiesRouteImport } from './routes/farmer/activities'
import { Route as FarmerAddActivityRouteImport } from './routes/farmer/add-activity'
import { Route as FarmerAnalyticsRouteImport } from './routes/farmer/analytics'
import { Route as FarmerAvailabilityRouteImport } from './routes/farmer/availability'
import { Route as FarmerBoardRouteImport } from './routes/farmer/board'
import { Route as FarmerBookingsRouteImport } from './routes/farmer/bookings'
import { Route as FarmerCalendarRouteImport } from './routes/farmer/calendar'
import { Route as FarmerCollaborationsRouteImport } from './routes/farmer/collaborations'
import { Route as FarmerCreateFarmRouteImport } from './routes/farmer/create-farm'
import { Route as FarmerCreatorRequestsRouteImport } from './routes/farmer/creator-requests'
import { Route as FarmerCropCalendarRouteImport } from './routes/farmer/crop-calendar'
import { Route as FarmerHelpRouteImport } from './routes/farmer/help'
import { Route as FarmerHistoryRouteImport } from './routes/farmer/history'
import { Route as FarmerHomeRouteImport } from './routes/farmer/home'
import { Route as FarmerListingsRouteImport } from './routes/farmer/listings'
import { Route as FarmerMessagesRouteImport } from './routes/farmer/messages'
import { Route as FarmerNotificationsRouteImport } from './routes/farmer/notifications'
import { Route as FarmerPaymentsRouteImport } from './routes/farmer/payments'
import { Route as FarmerProfileRouteImport } from './routes/farmer/profile'
import { Route as FarmerReportsRouteImport } from './routes/farmer/reports'
import { Route as FarmerRequestsRouteImport } from './routes/farmer/requests'
import { Route as FarmerRevenueRouteImport } from './routes/farmer/revenue'
import { Route as FarmerSettingsRouteImport } from './routes/farmer/settings'
import { Route as FarmerWeatherRouteImport } from './routes/farmer/weather'
import { Route as FarmercardSlugRouteImport } from './routes/farmercard/$slug'
import { Route as TouristActivitiesRouteImport } from './routes/tourist/activities'
import { Route as TouristBookingDetailRouteImport } from './routes/tourist/booking-detail'
import { Route as TouristBookingsRouteImport } from './routes/tourist/bookings'
import { Route as TouristChecklistRouteImport } from './routes/tourist/checklist'
import { Route as TouristExperiencesRouteImport } from './routes/tourist/experiences'
import { Route as TouristExploreRouteImport } from './routes/tourist/explore'
import { Route as TouristHelpRouteImport } from './routes/tourist/help'
import { Route as TouristHistoryRouteImport } from './routes/tourist/history'
import { Route as TouristHomeRouteImport } from './routes/tourist/home'
import { Route as TouristMessagesRouteImport } from './routes/tourist/messages'
import { Route as TouristNearbyRouteImport } from './routes/tourist/nearby'
import { Route as TouristNotificationsRouteImport } from './routes/tourist/notifications'
import { Route as TouristPaymentsRouteImport } from './routes/tourist/payments'
import { Route as TouristProfileRouteImport } from './routes/tourist/profile'
import { Route as TouristReviewsRouteImport } from './routes/tourist/reviews'
import { Route as TouristSavedRoutesRouteImport } from './routes/tourist/saved-routes'
import { Route as TouristSettingsRouteImport } from './routes/tourist/settings'
import { Route as TouristTripPlannerRouteImport } from './routes/tourist/trip-planner'
import { Route as TouristWishlistRouteImport } from './routes/tourist/wishlist'
import { Route as FarmerListingIdRouteImport } from './routes/farmer/listing/$id'
import { Route as FarmerListingNewRouteImport } from './routes/farmer/listing/new'
import { Route as ServicesCreatorRegisterRouteImport } from './routes/services/creator/register'
import { Route as ServicesFarmerRegisterRouteImport } from './routes/services/farmer/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AITripPlannerRoute = AITripPlannerRouteImport.update({
  id: '/AI-trip-planner',
  path: '/AI-trip-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityApprovalRoute = AdminActivityApprovalRouteImport.update({
  id: '/admin/activity-approval',
  path: '/admin/activity-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminApprovalsRoute = AdminApprovalsRouteImport.update({
  id: '/admin/approvals',
  path: '/admin/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBlogsRoute = AdminBlogsRouteImport.update({
  id: '/admin/blogs',
  path: '/admin/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFarmApprovalRoute = AdminFarmApprovalRouteImport.update({
  id: '/admin/farm-approval',
  path: '/admin/farm-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFraudRoute = AdminFraudRouteImport.update({
  id: '/admin/fraud',
  path: '/admin/fraud',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHelpRoute = AdminHelpRouteImport.update({
  id: '/admin/help',
  path: '/admin/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHomeRoute = AdminHomeRouteImport.update({
  id: '/admin/home',
  path: '/admin/home',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin/support',
  path: '/admin/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifiedUsersRoute = AdminVerifiedUsersRouteImport.update({
  id: '/admin/verified-users',
  path: '/admin/verified-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVerifyRoute = AdminVerifyRouteImport.update({
  id: '/admin/verify',
  path: '/admin/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChangePasswordRoute = AuthChangePasswordRouteImport.update({
  id: '/auth/change-password',
  path: '/auth/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthChange_passwordRoute = AuthChange_passwordRouteImport.update({
  id: '/auth/change_password',
  path: '/auth/change_password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIdRoute = BlogIdRouteImport.update({
  id: '/blog/$id',
  path: '/blog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorAnalyticsRoute = CreatorAnalyticsRouteImport.update({
  id: '/creator/analytics',
  path: '/creator/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorBoardRoute = CreatorBoardRouteImport.update({
  id: '/creator/board',
  path: '/creator/board',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorBookingsRoute = CreatorBookingsRouteImport.update({
  id: '/creator/bookings',
  path: '/creator/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorBrandDealsRoute = CreatorBrandDealsRouteImport.update({
  id: '/creator/brand-deals',
  path: '/creator/brand-deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorCollaborationsRoute = CreatorCollaborationsRouteImport.update({
  id: '/creator/collaborations',
  path: '/creator/collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorFollowersRoute = CreatorFollowersRouteImport.update({
  id: '/creator/followers',
  path: '/creator/followers',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHelpRoute = CreatorHelpRouteImport.update({
  id: '/creator/help',
  path: '/creator/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorHomeRoute = CreatorHomeRouteImport.update({
  id: '/creator/home',
  path: '/creator/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorInstagramRoute = CreatorInstagramRouteImport.update({
  id: '/creator/instagram',
  path: '/creator/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorMessagesRoute = CreatorMessagesRouteImport.update({
  id: '/creator/messages',
  path: '/creator/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorNotificationsRoute = CreatorNotificationsRouteImport.update({
  id: '/creator/notifications',
  path: '/creator/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorPaymentsRoute = CreatorPaymentsRouteImport.update({
  id: '/creator/payments',
  path: '/creator/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorPortfolioRoute = CreatorPortfolioRouteImport.update({
  id: '/creator/portfolio',
  path: '/creator/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorProfileRoute = CreatorProfileRouteImport.update({
  id: '/creator/profile',
  path: '/creator/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorReportsRoute = CreatorReportsRouteImport.update({
  id: '/creator/reports',
  path: '/creator/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRevenueRoute = CreatorRevenueRouteImport.update({
  id: '/creator/revenue',
  path: '/creator/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSavedFarmsRoute = CreatorSavedFarmsRouteImport.update({
  id: '/creator/saved-farms',
  path: '/creator/saved-farms',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSettingsRoute = CreatorSettingsRouteImport.update({
  id: '/creator/settings',
  path: '/creator/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorSocialRoute = CreatorSocialRouteImport.update({
  id: '/creator/social',
  path: '/creator/social',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorYoutubeRoute = CreatorYoutubeRouteImport.update({
  id: '/creator/youtube',
  path: '/creator/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorcardSlugRoute = CreatorcardSlugRouteImport.update({
  id: '/creatorcard/$slug',
  path: '/creatorcard/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerActivitiesRoute = FarmerActivitiesRouteImport.update({
  id: '/farmer/activities',
  path: '/farmer/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerAddActivityRoute = FarmerAddActivityRouteImport.update({
  id: '/farmer/add-activity',
  path: '/farmer/add-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerAnalyticsRoute = FarmerAnalyticsRouteImport.update({
  id: '/farmer/analytics',
  path: '/farmer/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerAvailabilityRoute = FarmerAvailabilityRouteImport.update({
  id: '/farmer/availability',
  path: '/farmer/availability',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerBoardRoute = FarmerBoardRouteImport.update({
  id: '/farmer/board',
  path: '/farmer/board',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerBookingsRoute = FarmerBookingsRouteImport.update({
  id: '/farmer/bookings',
  path: '/farmer/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerCalendarRoute = FarmerCalendarRouteImport.update({
  id: '/farmer/calendar',
  path: '/farmer/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerCollaborationsRoute = FarmerCollaborationsRouteImport.update({
  id: '/farmer/collaborations',
  path: '/farmer/collaborations',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerCreateFarmRoute = FarmerCreateFarmRouteImport.update({
  id: '/farmer/create-farm',
  path: '/farmer/create-farm',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerCreatorRequestsRoute = FarmerCreatorRequestsRouteImport.update({
  id: '/farmer/creator-requests',
  path: '/farmer/creator-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerCropCalendarRoute = FarmerCropCalendarRouteImport.update({
  id: '/farmer/crop-calendar',
  path: '/farmer/crop-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerHelpRoute = FarmerHelpRouteImport.update({
  id: '/farmer/help',
  path: '/farmer/help',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerHistoryRoute = FarmerHistoryRouteImport.update({
  id: '/farmer/history',
  path: '/farmer/history',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerHomeRoute = FarmerHomeRouteImport.update({
  id: '/farmer/home',
  path: '/farmer/home',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerListingsRoute = FarmerListingsRouteImport.update({
  id: '/farmer/listings',
  path: '/farmer/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerMessagesRoute = FarmerMessagesRouteImport.update({
  id: '/farmer/messages',
  path: '/farmer/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerNotificationsRoute = FarmerNotificationsRouteImport.update({
  id: '/farmer/notifications',
  path: '/farmer/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerPaymentsRoute = FarmerPaymentsRouteImport.update({
  id: '/farmer/payments',
  path: '/farmer/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerProfileRoute = FarmerProfileRouteImport.update({
  id: '/farmer/profile',
  path: '/farmer/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerReportsRoute = FarmerReportsRouteImport.update({
  id: '/farmer/reports',
  path: '/farmer/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRequestsRoute = FarmerRequestsRouteImport.update({
  id: '/farmer/requests',
  path: '/farmer/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerRevenueRoute = FarmerRevenueRouteImport.update({
  id: '/farmer/revenue',
  path: '/farmer/revenue',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerSettingsRoute = FarmerSettingsRouteImport.update({
  id: '/farmer/settings',
  path: '/farmer/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerWeatherRoute = FarmerWeatherRouteImport.update({
  id: '/farmer/weather',
  path: '/farmer/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmercardSlugRoute = FarmercardSlugRouteImport.update({
  id: '/farmercard/$slug',
  path: '/farmercard/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristActivitiesRoute = TouristActivitiesRouteImport.update({
  id: '/tourist/activities',
  path: '/tourist/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristBookingDetailRoute = TouristBookingDetailRouteImport.update({
  id: '/tourist/booking-detail',
  path: '/tourist/booking-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristBookingsRoute = TouristBookingsRouteImport.update({
  id: '/tourist/bookings',
  path: '/tourist/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristChecklistRoute = TouristChecklistRouteImport.update({
  id: '/tourist/checklist',
  path: '/tourist/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristExperiencesRoute = TouristExperiencesRouteImport.update({
  id: '/tourist/experiences',
  path: '/tourist/experiences',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristExploreRoute = TouristExploreRouteImport.update({
  id: '/tourist/explore',
  path: '/tourist/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristHelpRoute = TouristHelpRouteImport.update({
  id: '/tourist/help',
  path: '/tourist/help',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristHistoryRoute = TouristHistoryRouteImport.update({
  id: '/tourist/history',
  path: '/tourist/history',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristHomeRoute = TouristHomeRouteImport.update({
  id: '/tourist/home',
  path: '/tourist/home',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristMessagesRoute = TouristMessagesRouteImport.update({
  id: '/tourist/messages',
  path: '/tourist/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristNearbyRoute = TouristNearbyRouteImport.update({
  id: '/tourist/nearby',
  path: '/tourist/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristNotificationsRoute = TouristNotificationsRouteImport.update({
  id: '/tourist/notifications',
  path: '/tourist/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristPaymentsRoute = TouristPaymentsRouteImport.update({
  id: '/tourist/payments',
  path: '/tourist/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristProfileRoute = TouristProfileRouteImport.update({
  id: '/tourist/profile',
  path: '/tourist/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristReviewsRoute = TouristReviewsRouteImport.update({
  id: '/tourist/reviews',
  path: '/tourist/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristSavedRoutesRoute = TouristSavedRoutesRouteImport.update({
  id: '/tourist/saved-routes',
  path: '/tourist/saved-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristSettingsRoute = TouristSettingsRouteImport.update({
  id: '/tourist/settings',
  path: '/tourist/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristTripPlannerRoute = TouristTripPlannerRouteImport.update({
  id: '/tourist/trip-planner',
  path: '/tourist/trip-planner',
  getParentRoute: () => rootRouteImport,
} as any)
const TouristWishlistRoute = TouristWishlistRouteImport.update({
  id: '/tourist/wishlist',
  path: '/tourist/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerListingIdRoute = FarmerListingIdRouteImport.update({
  id: '/farmer/listing/$id',
  path: '/farmer/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmerListingNewRoute = FarmerListingNewRouteImport.update({
  id: '/farmer/listing/new',
  path: '/farmer/listing/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCreatorRegisterRoute = ServicesCreatorRegisterRouteImport.update({
  id: '/creator/register',
  path: '/creator/register',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFarmerRegisterRoute = ServicesFarmerRegisterRouteImport.update({
  id: '/farmer/register',
  path: '/farmer/register',
  getParentRoute: () => ServicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/AI-trip-planner': typeof AITripPlannerRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/activity-approval': typeof AdminActivityApprovalRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/farm-approval': typeof AdminFarmApprovalRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verified-users': typeof AdminVerifiedUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/change_password': typeof AuthChange_passwordRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$id': typeof BlogIdRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/board': typeof CreatorBoardRoute
  '/creator/bookings': typeof CreatorBookingsRoute
  '/creator/brand-deals': typeof CreatorBrandDealsRoute
  '/creator/collaborations': typeof CreatorCollaborationsRoute
  '/creator/followers': typeof CreatorFollowersRoute
  '/creator/help': typeof CreatorHelpRoute
  '/creator/home': typeof CreatorHomeRoute
  '/creator/instagram': typeof CreatorInstagramRoute
  '/creator/messages': typeof CreatorMessagesRoute
  '/creator/notifications': typeof CreatorNotificationsRoute
  '/creator/payments': typeof CreatorPaymentsRoute
  '/creator/portfolio': typeof CreatorPortfolioRoute
  '/creator/profile': typeof CreatorProfileRoute
  '/creator/reports': typeof CreatorReportsRoute
  '/creator/revenue': typeof CreatorRevenueRoute
  '/creator/saved-farms': typeof CreatorSavedFarmsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/social': typeof CreatorSocialRoute
  '/creator/youtube': typeof CreatorYoutubeRoute
  '/creatorcard/$slug': typeof CreatorcardSlugRoute
  '/farmer/activities': typeof FarmerActivitiesRoute
  '/farmer/add-activity': typeof FarmerAddActivityRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/availability': typeof FarmerAvailabilityRoute
  '/farmer/board': typeof FarmerBoardRoute
  '/farmer/bookings': typeof FarmerBookingsRoute
  '/farmer/calendar': typeof FarmerCalendarRoute
  '/farmer/collaborations': typeof FarmerCollaborationsRoute
  '/farmer/create-farm': typeof FarmerCreateFarmRoute
  '/farmer/creator-requests': typeof FarmerCreatorRequestsRoute
  '/farmer/crop-calendar': typeof FarmerCropCalendarRoute
  '/farmer/help': typeof FarmerHelpRoute
  '/farmer/history': typeof FarmerHistoryRoute
  '/farmer/home': typeof FarmerHomeRoute
  '/farmer/listings': typeof FarmerListingsRoute
  '/farmer/messages': typeof FarmerMessagesRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/reports': typeof FarmerReportsRoute
  '/farmer/requests': typeof FarmerRequestsRoute
  '/farmer/revenue': typeof FarmerRevenueRoute
  '/farmer/settings': typeof FarmerSettingsRoute
  '/farmer/weather': typeof FarmerWeatherRoute
  '/farmercard/$slug': typeof FarmercardSlugRoute
  '/tourist/activities': typeof TouristActivitiesRoute
  '/tourist/booking-detail': typeof TouristBookingDetailRoute
  '/tourist/bookings': typeof TouristBookingsRoute
  '/tourist/checklist': typeof TouristChecklistRoute
  '/tourist/experiences': typeof TouristExperiencesRoute
  '/tourist/explore': typeof TouristExploreRoute
  '/tourist/help': typeof TouristHelpRoute
  '/tourist/history': typeof TouristHistoryRoute
  '/tourist/home': typeof TouristHomeRoute
  '/tourist/messages': typeof TouristMessagesRoute
  '/tourist/nearby': typeof TouristNearbyRoute
  '/tourist/notifications': typeof TouristNotificationsRoute
  '/tourist/payments': typeof TouristPaymentsRoute
  '/tourist/profile': typeof TouristProfileRoute
  '/tourist/reviews': typeof TouristReviewsRoute
  '/tourist/saved-routes': typeof TouristSavedRoutesRoute
  '/tourist/settings': typeof TouristSettingsRoute
  '/tourist/trip-planner': typeof TouristTripPlannerRoute
  '/tourist/wishlist': typeof TouristWishlistRoute
  '/blog/': typeof BlogIndexRoute
  '/farmer/listing/$id': typeof FarmerListingIdRoute
  '/farmer/listing/new': typeof FarmerListingNewRoute
  '/services/creator/register': typeof ServicesCreatorRegisterRoute
  '/services/farmer/register': typeof ServicesFarmerRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/AI-trip-planner': typeof AITripPlannerRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/activity-approval': typeof AdminActivityApprovalRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/farm-approval': typeof AdminFarmApprovalRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verified-users': typeof AdminVerifiedUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/change_password': typeof AuthChange_passwordRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$id': typeof BlogIdRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/board': typeof CreatorBoardRoute
  '/creator/bookings': typeof CreatorBookingsRoute
  '/creator/brand-deals': typeof CreatorBrandDealsRoute
  '/creator/collaborations': typeof CreatorCollaborationsRoute
  '/creator/followers': typeof CreatorFollowersRoute
  '/creator/help': typeof CreatorHelpRoute
  '/creator/home': typeof CreatorHomeRoute
  '/creator/instagram': typeof CreatorInstagramRoute
  '/creator/messages': typeof CreatorMessagesRoute
  '/creator/notifications': typeof CreatorNotificationsRoute
  '/creator/payments': typeof CreatorPaymentsRoute
  '/creator/portfolio': typeof CreatorPortfolioRoute
  '/creator/profile': typeof CreatorProfileRoute
  '/creator/reports': typeof CreatorReportsRoute
  '/creator/revenue': typeof CreatorRevenueRoute
  '/creator/saved-farms': typeof CreatorSavedFarmsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/social': typeof CreatorSocialRoute
  '/creator/youtube': typeof CreatorYoutubeRoute
  '/creatorcard/$slug': typeof CreatorcardSlugRoute
  '/farmer/activities': typeof FarmerActivitiesRoute
  '/farmer/add-activity': typeof FarmerAddActivityRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/availability': typeof FarmerAvailabilityRoute
  '/farmer/board': typeof FarmerBoardRoute
  '/farmer/bookings': typeof FarmerBookingsRoute
  '/farmer/calendar': typeof FarmerCalendarRoute
  '/farmer/collaborations': typeof FarmerCollaborationsRoute
  '/farmer/create-farm': typeof FarmerCreateFarmRoute
  '/farmer/creator-requests': typeof FarmerCreatorRequestsRoute
  '/farmer/crop-calendar': typeof FarmerCropCalendarRoute
  '/farmer/help': typeof FarmerHelpRoute
  '/farmer/history': typeof FarmerHistoryRoute
  '/farmer/home': typeof FarmerHomeRoute
  '/farmer/listings': typeof FarmerListingsRoute
  '/farmer/messages': typeof FarmerMessagesRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/reports': typeof FarmerReportsRoute
  '/farmer/requests': typeof FarmerRequestsRoute
  '/farmer/revenue': typeof FarmerRevenueRoute
  '/farmer/settings': typeof FarmerSettingsRoute
  '/farmer/weather': typeof FarmerWeatherRoute
  '/farmercard/$slug': typeof FarmercardSlugRoute
  '/tourist/activities': typeof TouristActivitiesRoute
  '/tourist/booking-detail': typeof TouristBookingDetailRoute
  '/tourist/bookings': typeof TouristBookingsRoute
  '/tourist/checklist': typeof TouristChecklistRoute
  '/tourist/experiences': typeof TouristExperiencesRoute
  '/tourist/explore': typeof TouristExploreRoute
  '/tourist/help': typeof TouristHelpRoute
  '/tourist/history': typeof TouristHistoryRoute
  '/tourist/home': typeof TouristHomeRoute
  '/tourist/messages': typeof TouristMessagesRoute
  '/tourist/nearby': typeof TouristNearbyRoute
  '/tourist/notifications': typeof TouristNotificationsRoute
  '/tourist/payments': typeof TouristPaymentsRoute
  '/tourist/profile': typeof TouristProfileRoute
  '/tourist/reviews': typeof TouristReviewsRoute
  '/tourist/saved-routes': typeof TouristSavedRoutesRoute
  '/tourist/settings': typeof TouristSettingsRoute
  '/tourist/trip-planner': typeof TouristTripPlannerRoute
  '/tourist/wishlist': typeof TouristWishlistRoute
  '/blog': typeof BlogIndexRoute
  '/farmer/listing/$id': typeof FarmerListingIdRoute
  '/farmer/listing/new': typeof FarmerListingNewRoute
  '/services/creator/register': typeof ServicesCreatorRegisterRoute
  '/services/farmer/register': typeof ServicesFarmerRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/AI-trip-planner': typeof AITripPlannerRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRouteWithChildren
  '/admin/activity-approval': typeof AdminActivityApprovalRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approvals': typeof AdminApprovalsRoute
  '/admin/blogs': typeof AdminBlogsRoute
  '/admin/farm-approval': typeof AdminFarmApprovalRoute
  '/admin/fraud': typeof AdminFraudRoute
  '/admin/help': typeof AdminHelpRoute
  '/admin/home': typeof AdminHomeRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/verified-users': typeof AdminVerifiedUsersRoute
  '/admin/verify': typeof AdminVerifyRoute
  '/auth/change-password': typeof AuthChangePasswordRoute
  '/auth/change_password': typeof AuthChange_passwordRoute
  '/auth/login': typeof AuthLoginRoute
  '/blog/$id': typeof BlogIdRoute
  '/creator/analytics': typeof CreatorAnalyticsRoute
  '/creator/board': typeof CreatorBoardRoute
  '/creator/bookings': typeof CreatorBookingsRoute
  '/creator/brand-deals': typeof CreatorBrandDealsRoute
  '/creator/collaborations': typeof CreatorCollaborationsRoute
  '/creator/followers': typeof CreatorFollowersRoute
  '/creator/help': typeof CreatorHelpRoute
  '/creator/home': typeof CreatorHomeRoute
  '/creator/instagram': typeof CreatorInstagramRoute
  '/creator/messages': typeof CreatorMessagesRoute
  '/creator/notifications': typeof CreatorNotificationsRoute
  '/creator/payments': typeof CreatorPaymentsRoute
  '/creator/portfolio': typeof CreatorPortfolioRoute
  '/creator/profile': typeof CreatorProfileRoute
  '/creator/reports': typeof CreatorReportsRoute
  '/creator/revenue': typeof CreatorRevenueRoute
  '/creator/saved-farms': typeof CreatorSavedFarmsRoute
  '/creator/settings': typeof CreatorSettingsRoute
  '/creator/social': typeof CreatorSocialRoute
  '/creator/youtube': typeof CreatorYoutubeRoute
  '/creatorcard/$slug': typeof CreatorcardSlugRoute
  '/farmer/activities': typeof FarmerActivitiesRoute
  '/farmer/add-activity': typeof FarmerAddActivityRoute
  '/farmer/analytics': typeof FarmerAnalyticsRoute
  '/farmer/availability': typeof FarmerAvailabilityRoute
  '/farmer/board': typeof FarmerBoardRoute
  '/farmer/bookings': typeof FarmerBookingsRoute
  '/farmer/calendar': typeof FarmerCalendarRoute
  '/farmer/collaborations': typeof FarmerCollaborationsRoute
  '/farmer/create-farm': typeof FarmerCreateFarmRoute
  '/farmer/creator-requests': typeof FarmerCreatorRequestsRoute
  '/farmer/crop-calendar': typeof FarmerCropCalendarRoute
  '/farmer/help': typeof FarmerHelpRoute
  '/farmer/history': typeof FarmerHistoryRoute
  '/farmer/home': typeof FarmerHomeRoute
  '/farmer/listings': typeof FarmerListingsRoute
  '/farmer/messages': typeof FarmerMessagesRoute
  '/farmer/notifications': typeof FarmerNotificationsRoute
  '/farmer/payments': typeof FarmerPaymentsRoute
  '/farmer/profile': typeof FarmerProfileRoute
  '/farmer/reports': typeof FarmerReportsRoute
  '/farmer/requests': typeof FarmerRequestsRoute
  '/farmer/revenue': typeof FarmerRevenueRoute
  '/farmer/settings': typeof FarmerSettingsRoute
  '/farmer/weather': typeof FarmerWeatherRoute
  '/farmercard/$slug': typeof FarmercardSlugRoute
  '/tourist/activities': typeof TouristActivitiesRoute
  '/tourist/booking-detail': typeof TouristBookingDetailRoute
  '/tourist/bookings': typeof TouristBookingsRoute
  '/tourist/checklist': typeof TouristChecklistRoute
  '/tourist/experiences': typeof TouristExperiencesRoute
  '/tourist/explore': typeof TouristExploreRoute
  '/tourist/help': typeof TouristHelpRoute
  '/tourist/history': typeof TouristHistoryRoute
  '/tourist/home': typeof TouristHomeRoute
  '/tourist/messages': typeof TouristMessagesRoute
  '/tourist/nearby': typeof TouristNearbyRoute
  '/tourist/notifications': typeof TouristNotificationsRoute
  '/tourist/payments': typeof TouristPaymentsRoute
  '/tourist/profile': typeof TouristProfileRoute
  '/tourist/reviews': typeof TouristReviewsRoute
  '/tourist/saved-routes': typeof TouristSavedRoutesRoute
  '/tourist/settings': typeof TouristSettingsRoute
  '/tourist/trip-planner': typeof TouristTripPlannerRoute
  '/tourist/wishlist': typeof TouristWishlistRoute
  '/blog/': typeof BlogIndexRoute
  '/farmer/listing/$id': typeof FarmerListingIdRoute
  '/farmer/listing/new': typeof FarmerListingNewRoute
  '/services/creator/register': typeof ServicesCreatorRegisterRoute
  '/services/farmer/register': typeof ServicesFarmerRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/AI-trip-planner'
    | '/about'
    | '/contact'
    | '/home'
    | '/login'
    | '/search'
    | '/services'
    | '/admin/activity-approval'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/blogs'
    | '/admin/farm-approval'
    | '/admin/fraud'
    | '/admin/help'
    | '/admin/home'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verified-users'
    | '/admin/verify'
    | '/auth/change-password'
    | '/auth/change_password'
    | '/auth/login'
    | '/blog/$id'
    | '/creator/analytics'
    | '/creator/board'
    | '/creator/bookings'
    | '/creator/brand-deals'
    | '/creator/collaborations'
    | '/creator/followers'
    | '/creator/help'
    | '/creator/home'
    | '/creator/instagram'
    | '/creator/messages'
    | '/creator/notifications'
    | '/creator/payments'
    | '/creator/portfolio'
    | '/creator/profile'
    | '/creator/reports'
    | '/creator/revenue'
    | '/creator/saved-farms'
    | '/creator/settings'
    | '/creator/social'
    | '/creator/youtube'
    | '/creatorcard/$slug'
    | '/farmer/activities'
    | '/farmer/add-activity'
    | '/farmer/analytics'
    | '/farmer/availability'
    | '/farmer/board'
    | '/farmer/bookings'
    | '/farmer/calendar'
    | '/farmer/collaborations'
    | '/farmer/create-farm'
    | '/farmer/creator-requests'
    | '/farmer/crop-calendar'
    | '/farmer/help'
    | '/farmer/history'
    | '/farmer/home'
    | '/farmer/listings'
    | '/farmer/messages'
    | '/farmer/notifications'
    | '/farmer/payments'
    | '/farmer/profile'
    | '/farmer/reports'
    | '/farmer/requests'
    | '/farmer/revenue'
    | '/farmer/settings'
    | '/farmer/weather'
    | '/farmercard/$slug'
    | '/tourist/activities'
    | '/tourist/booking-detail'
    | '/tourist/bookings'
    | '/tourist/checklist'
    | '/tourist/experiences'
    | '/tourist/explore'
    | '/tourist/help'
    | '/tourist/history'
    | '/tourist/home'
    | '/tourist/messages'
    | '/tourist/nearby'
    | '/tourist/notifications'
    | '/tourist/payments'
    | '/tourist/profile'
    | '/tourist/reviews'
    | '/tourist/saved-routes'
    | '/tourist/settings'
    | '/tourist/trip-planner'
    | '/tourist/wishlist'
    | '/blog/'
    | '/farmer/listing/$id'
    | '/farmer/listing/new'
    | '/services/creator/register'
    | '/services/farmer/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/AI-trip-planner'
    | '/about'
    | '/contact'
    | '/home'
    | '/login'
    | '/search'
    | '/services'
    | '/admin/activity-approval'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/blogs'
    | '/admin/farm-approval'
    | '/admin/fraud'
    | '/admin/help'
    | '/admin/home'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verified-users'
    | '/admin/verify'
    | '/auth/change-password'
    | '/auth/change_password'
    | '/auth/login'
    | '/blog/$id'
    | '/creator/analytics'
    | '/creator/board'
    | '/creator/bookings'
    | '/creator/brand-deals'
    | '/creator/collaborations'
    | '/creator/followers'
    | '/creator/help'
    | '/creator/home'
    | '/creator/instagram'
    | '/creator/messages'
    | '/creator/notifications'
    | '/creator/payments'
    | '/creator/portfolio'
    | '/creator/profile'
    | '/creator/reports'
    | '/creator/revenue'
    | '/creator/saved-farms'
    | '/creator/settings'
    | '/creator/social'
    | '/creator/youtube'
    | '/creatorcard/$slug'
    | '/farmer/activities'
    | '/farmer/add-activity'
    | '/farmer/analytics'
    | '/farmer/availability'
    | '/farmer/board'
    | '/farmer/bookings'
    | '/farmer/calendar'
    | '/farmer/collaborations'
    | '/farmer/create-farm'
    | '/farmer/creator-requests'
    | '/farmer/crop-calendar'
    | '/farmer/help'
    | '/farmer/history'
    | '/farmer/home'
    | '/farmer/listings'
    | '/farmer/messages'
    | '/farmer/notifications'
    | '/farmer/payments'
    | '/farmer/profile'
    | '/farmer/reports'
    | '/farmer/requests'
    | '/farmer/revenue'
    | '/farmer/settings'
    | '/farmer/weather'
    | '/farmercard/$slug'
    | '/tourist/activities'
    | '/tourist/booking-detail'
    | '/tourist/bookings'
    | '/tourist/checklist'
    | '/tourist/experiences'
    | '/tourist/explore'
    | '/tourist/help'
    | '/tourist/history'
    | '/tourist/home'
    | '/tourist/messages'
    | '/tourist/nearby'
    | '/tourist/notifications'
    | '/tourist/payments'
    | '/tourist/profile'
    | '/tourist/reviews'
    | '/tourist/saved-routes'
    | '/tourist/settings'
    | '/tourist/trip-planner'
    | '/tourist/wishlist'
    | '/blog'
    | '/farmer/listing/$id'
    | '/farmer/listing/new'
    | '/services/creator/register'
    | '/services/farmer/register'
  id:
    | '__root__'
    | '/'
    | '/AI-trip-planner'
    | '/about'
    | '/contact'
    | '/home'
    | '/login'
    | '/search'
    | '/services'
    | '/admin/activity-approval'
    | '/admin/analytics'
    | '/admin/approvals'
    | '/admin/blogs'
    | '/admin/farm-approval'
    | '/admin/fraud'
    | '/admin/help'
    | '/admin/home'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verified-users'
    | '/admin/verify'
    | '/auth/change-password'
    | '/auth/change_password'
    | '/auth/login'
    | '/blog/$id'
    | '/creator/analytics'
    | '/creator/board'
    | '/creator/bookings'
    | '/creator/brand-deals'
    | '/creator/collaborations'
    | '/creator/followers'
    | '/creator/help'
    | '/creator/home'
    | '/creator/instagram'
    | '/creator/messages'
    | '/creator/notifications'
    | '/creator/payments'
    | '/creator/portfolio'
    | '/creator/profile'
    | '/creator/reports'
    | '/creator/revenue'
    | '/creator/saved-farms'
    | '/creator/settings'
    | '/creator/social'
    | '/creator/youtube'
    | '/creatorcard/$slug'
    | '/farmer/activities'
    | '/farmer/add-activity'
    | '/farmer/analytics'
    | '/farmer/availability'
    | '/farmer/board'
    | '/farmer/bookings'
    | '/farmer/calendar'
    | '/farmer/collaborations'
    | '/farmer/create-farm'
    | '/farmer/creator-requests'
    | '/farmer/crop-calendar'
    | '/farmer/help'
    | '/farmer/history'
    | '/farmer/home'
    | '/farmer/listings'
    | '/farmer/messages'
    | '/farmer/notifications'
    | '/farmer/payments'
    | '/farmer/profile'
    | '/farmer/reports'
    | '/farmer/requests'
    | '/farmer/revenue'
    | '/farmer/settings'
    | '/farmer/weather'
    | '/farmercard/$slug'
    | '/tourist/activities'
    | '/tourist/booking-detail'
    | '/tourist/bookings'
    | '/tourist/checklist'
    | '/tourist/experiences'
    | '/tourist/explore'
    | '/tourist/help'
    | '/tourist/history'
    | '/tourist/home'
    | '/tourist/messages'
    | '/tourist/nearby'
    | '/tourist/notifications'
    | '/tourist/payments'
    | '/tourist/profile'
    | '/tourist/reviews'
    | '/tourist/saved-routes'
    | '/tourist/settings'
    | '/tourist/trip-planner'
    | '/tourist/wishlist'
    | '/blog/'
    | '/farmer/listing/$id'
    | '/farmer/listing/new'
    | '/services/creator/register'
    | '/services/farmer/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AITripPlannerRoute: typeof AITripPlannerRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AdminActivityApprovalRoute: typeof AdminActivityApprovalRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApprovalsRoute: typeof AdminApprovalsRoute
  AdminBlogsRoute: typeof AdminBlogsRoute
  AdminFarmApprovalRoute: typeof AdminFarmApprovalRoute
  AdminFraudRoute: typeof AdminFraudRoute
  AdminHelpRoute: typeof AdminHelpRoute
  AdminHomeRoute: typeof AdminHomeRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVerifiedUsersRoute: typeof AdminVerifiedUsersRoute
  AdminVerifyRoute: typeof AdminVerifyRoute
  AuthChangePasswordRoute: typeof AuthChangePasswordRoute
  AuthChange_passwordRoute: typeof AuthChange_passwordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  BlogIdRoute: typeof BlogIdRoute
  CreatorAnalyticsRoute: typeof CreatorAnalyticsRoute
  CreatorBoardRoute: typeof CreatorBoardRoute
  CreatorBookingsRoute: typeof CreatorBookingsRoute
  CreatorBrandDealsRoute: typeof CreatorBrandDealsRoute
  CreatorCollaborationsRoute: typeof CreatorCollaborationsRoute
  CreatorFollowersRoute: typeof CreatorFollowersRoute
  CreatorHelpRoute: typeof CreatorHelpRoute
  CreatorHomeRoute: typeof CreatorHomeRoute
  CreatorInstagramRoute: typeof CreatorInstagramRoute
  CreatorMessagesRoute: typeof CreatorMessagesRoute
  CreatorNotificationsRoute: typeof CreatorNotificationsRoute
  CreatorPaymentsRoute: typeof CreatorPaymentsRoute
  CreatorPortfolioRoute: typeof CreatorPortfolioRoute
  CreatorProfileRoute: typeof CreatorProfileRoute
  CreatorReportsRoute: typeof CreatorReportsRoute
  CreatorRevenueRoute: typeof CreatorRevenueRoute
  CreatorSavedFarmsRoute: typeof CreatorSavedFarmsRoute
  CreatorSettingsRoute: typeof CreatorSettingsRoute
  CreatorSocialRoute: typeof CreatorSocialRoute
  CreatorYoutubeRoute: typeof CreatorYoutubeRoute
  CreatorcardSlugRoute: typeof CreatorcardSlugRoute
  FarmerActivitiesRoute: typeof FarmerActivitiesRoute
  FarmerAddActivityRoute: typeof FarmerAddActivityRoute
  FarmerAnalyticsRoute: typeof FarmerAnalyticsRoute
  FarmerAvailabilityRoute: typeof FarmerAvailabilityRoute
  FarmerBoardRoute: typeof FarmerBoardRoute
  FarmerBookingsRoute: typeof FarmerBookingsRoute
  FarmerCalendarRoute: typeof FarmerCalendarRoute
  FarmerCollaborationsRoute: typeof FarmerCollaborationsRoute
  FarmerCreateFarmRoute: typeof FarmerCreateFarmRoute
  FarmerCreatorRequestsRoute: typeof FarmerCreatorRequestsRoute
  FarmerCropCalendarRoute: typeof FarmerCropCalendarRoute
  FarmerHelpRoute: typeof FarmerHelpRoute
  FarmerHistoryRoute: typeof FarmerHistoryRoute
  FarmerHomeRoute: typeof FarmerHomeRoute
  FarmerListingsRoute: typeof FarmerListingsRoute
  FarmerMessagesRoute: typeof FarmerMessagesRoute
  FarmerNotificationsRoute: typeof FarmerNotificationsRoute
  FarmerPaymentsRoute: typeof FarmerPaymentsRoute
  FarmerProfileRoute: typeof FarmerProfileRoute
  FarmerReportsRoute: typeof FarmerReportsRoute
  FarmerRequestsRoute: typeof FarmerRequestsRoute
  FarmerRevenueRoute: typeof FarmerRevenueRoute
  FarmerSettingsRoute: typeof FarmerSettingsRoute
  FarmerWeatherRoute: typeof FarmerWeatherRoute
  FarmercardSlugRoute: typeof FarmercardSlugRoute
  TouristActivitiesRoute: typeof TouristActivitiesRoute
  TouristBookingDetailRoute: typeof TouristBookingDetailRoute
  TouristBookingsRoute: typeof TouristBookingsRoute
  TouristChecklistRoute: typeof TouristChecklistRoute
  TouristExperiencesRoute: typeof TouristExperiencesRoute
  TouristExploreRoute: typeof TouristExploreRoute
  TouristHelpRoute: typeof TouristHelpRoute
  TouristHistoryRoute: typeof TouristHistoryRoute
  TouristHomeRoute: typeof TouristHomeRoute
  TouristMessagesRoute: typeof TouristMessagesRoute
  TouristNearbyRoute: typeof TouristNearbyRoute
  TouristNotificationsRoute: typeof TouristNotificationsRoute
  TouristPaymentsRoute: typeof TouristPaymentsRoute
  TouristProfileRoute: typeof TouristProfileRoute
  TouristReviewsRoute: typeof TouristReviewsRoute
  TouristSavedRoutesRoute: typeof TouristSavedRoutesRoute
  TouristSettingsRoute: typeof TouristSettingsRoute
  TouristTripPlannerRoute: typeof TouristTripPlannerRoute
  TouristWishlistRoute: typeof TouristWishlistRoute
  BlogIndexRoute: typeof BlogIndexRoute
  FarmerListingIdRoute: typeof FarmerListingIdRoute
  FarmerListingNewRoute: typeof FarmerListingNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AI-trip-planner': {
      id: '/AI-trip-planner'
      path: '/AI-trip-planner'
      fullPath: '/AI-trip-planner'
      preLoaderRoute: typeof AITripPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/activity-approval': {
      id: '/admin/activity-approval'
      path: '/admin/activity-approval'
      fullPath: '/admin/activity-approval'
      preLoaderRoute: typeof AdminActivityApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/approvals': {
      id: '/admin/approvals'
      path: '/admin/approvals'
      fullPath: '/admin/approvals'
      preLoaderRoute: typeof AdminApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/blogs': {
      id: '/admin/blogs'
      path: '/admin/blogs'
      fullPath: '/admin/blogs'
      preLoaderRoute: typeof AdminBlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/farm-approval': {
      id: '/admin/farm-approval'
      path: '/admin/farm-approval'
      fullPath: '/admin/farm-approval'
      preLoaderRoute: typeof AdminFarmApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/fraud': {
      id: '/admin/fraud'
      path: '/admin/fraud'
      fullPath: '/admin/fraud'
      preLoaderRoute: typeof AdminFraudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/help': {
      id: '/admin/help'
      path: '/admin/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AdminHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/home': {
      id: '/admin/home'
      path: '/admin/home'
      fullPath: '/admin/home'
      preLoaderRoute: typeof AdminHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verified-users': {
      id: '/admin/verified-users'
      path: '/admin/verified-users'
      fullPath: '/admin/verified-users'
      preLoaderRoute: typeof AdminVerifiedUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/verify': {
      id: '/admin/verify'
      path: '/admin/verify'
      fullPath: '/admin/verify'
      preLoaderRoute: typeof AdminVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change-password': {
      id: '/auth/change-password'
      path: '/auth/change-password'
      fullPath: '/auth/change-password'
      preLoaderRoute: typeof AuthChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/change_password': {
      id: '/auth/change_password'
      path: '/auth/change_password'
      fullPath: '/auth/change_password'
      preLoaderRoute: typeof AuthChange_passwordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$id': {
      id: '/blog/$id'
      path: '/blog/$id'
      fullPath: '/blog/$id'
      preLoaderRoute: typeof BlogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/analytics': {
      id: '/creator/analytics'
      path: '/creator/analytics'
      fullPath: '/creator/analytics'
      preLoaderRoute: typeof CreatorAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/board': {
      id: '/creator/board'
      path: '/creator/board'
      fullPath: '/creator/board'
      preLoaderRoute: typeof CreatorBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/bookings': {
      id: '/creator/bookings'
      path: '/creator/bookings'
      fullPath: '/creator/bookings'
      preLoaderRoute: typeof CreatorBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/brand-deals': {
      id: '/creator/brand-deals'
      path: '/creator/brand-deals'
      fullPath: '/creator/brand-deals'
      preLoaderRoute: typeof CreatorBrandDealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/collaborations': {
      id: '/creator/collaborations'
      path: '/creator/collaborations'
      fullPath: '/creator/collaborations'
      preLoaderRoute: typeof CreatorCollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/followers': {
      id: '/creator/followers'
      path: '/creator/followers'
      fullPath: '/creator/followers'
      preLoaderRoute: typeof CreatorFollowersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/help': {
      id: '/creator/help'
      path: '/creator/help'
      fullPath: '/creator/help'
      preLoaderRoute: typeof CreatorHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/home': {
      id: '/creator/home'
      path: '/creator/home'
      fullPath: '/creator/home'
      preLoaderRoute: typeof CreatorHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/instagram': {
      id: '/creator/instagram'
      path: '/creator/instagram'
      fullPath: '/creator/instagram'
      preLoaderRoute: typeof CreatorInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/messages': {
      id: '/creator/messages'
      path: '/creator/messages'
      fullPath: '/creator/messages'
      preLoaderRoute: typeof CreatorMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/notifications': {
      id: '/creator/notifications'
      path: '/creator/notifications'
      fullPath: '/creator/notifications'
      preLoaderRoute: typeof CreatorNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/payments': {
      id: '/creator/payments'
      path: '/creator/payments'
      fullPath: '/creator/payments'
      preLoaderRoute: typeof CreatorPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/portfolio': {
      id: '/creator/portfolio'
      path: '/creator/portfolio'
      fullPath: '/creator/portfolio'
      preLoaderRoute: typeof CreatorPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/profile': {
      id: '/creator/profile'
      path: '/creator/profile'
      fullPath: '/creator/profile'
      preLoaderRoute: typeof CreatorProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/reports': {
      id: '/creator/reports'
      path: '/creator/reports'
      fullPath: '/creator/reports'
      preLoaderRoute: typeof CreatorReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/revenue': {
      id: '/creator/revenue'
      path: '/creator/revenue'
      fullPath: '/creator/revenue'
      preLoaderRoute: typeof CreatorRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/saved-farms': {
      id: '/creator/saved-farms'
      path: '/creator/saved-farms'
      fullPath: '/creator/saved-farms'
      preLoaderRoute: typeof CreatorSavedFarmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/settings': {
      id: '/creator/settings'
      path: '/creator/settings'
      fullPath: '/creator/settings'
      preLoaderRoute: typeof CreatorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/social': {
      id: '/creator/social'
      path: '/creator/social'
      fullPath: '/creator/social'
      preLoaderRoute: typeof CreatorSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator/youtube': {
      id: '/creator/youtube'
      path: '/creator/youtube'
      fullPath: '/creator/youtube'
      preLoaderRoute: typeof CreatorYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creatorcard/$slug': {
      id: '/creatorcard/$slug'
      path: '/creatorcard/$slug'
      fullPath: '/creatorcard/$slug'
      preLoaderRoute: typeof CreatorcardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/activities': {
      id: '/farmer/activities'
      path: '/farmer/activities'
      fullPath: '/farmer/activities'
      preLoaderRoute: typeof FarmerActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/add-activity': {
      id: '/farmer/add-activity'
      path: '/farmer/add-activity'
      fullPath: '/farmer/add-activity'
      preLoaderRoute: typeof FarmerAddActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/analytics': {
      id: '/farmer/analytics'
      path: '/farmer/analytics'
      fullPath: '/farmer/analytics'
      preLoaderRoute: typeof FarmerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/availability': {
      id: '/farmer/availability'
      path: '/farmer/availability'
      fullPath: '/farmer/availability'
      preLoaderRoute: typeof FarmerAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/board': {
      id: '/farmer/board'
      path: '/farmer/board'
      fullPath: '/farmer/board'
      preLoaderRoute: typeof FarmerBoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/bookings': {
      id: '/farmer/bookings'
      path: '/farmer/bookings'
      fullPath: '/farmer/bookings'
      preLoaderRoute: typeof FarmerBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/calendar': {
      id: '/farmer/calendar'
      path: '/farmer/calendar'
      fullPath: '/farmer/calendar'
      preLoaderRoute: typeof FarmerCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/collaborations': {
      id: '/farmer/collaborations'
      path: '/farmer/collaborations'
      fullPath: '/farmer/collaborations'
      preLoaderRoute: typeof FarmerCollaborationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/create-farm': {
      id: '/farmer/create-farm'
      path: '/farmer/create-farm'
      fullPath: '/farmer/create-farm'
      preLoaderRoute: typeof FarmerCreateFarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/creator-requests': {
      id: '/farmer/creator-requests'
      path: '/farmer/creator-requests'
      fullPath: '/farmer/creator-requests'
      preLoaderRoute: typeof FarmerCreatorRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/crop-calendar': {
      id: '/farmer/crop-calendar'
      path: '/farmer/crop-calendar'
      fullPath: '/farmer/crop-calendar'
      preLoaderRoute: typeof FarmerCropCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/help': {
      id: '/farmer/help'
      path: '/farmer/help'
      fullPath: '/farmer/help'
      preLoaderRoute: typeof FarmerHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/history': {
      id: '/farmer/history'
      path: '/farmer/history'
      fullPath: '/farmer/history'
      preLoaderRoute: typeof FarmerHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/home': {
      id: '/farmer/home'
      path: '/farmer/home'
      fullPath: '/farmer/home'
      preLoaderRoute: typeof FarmerHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/listings': {
      id: '/farmer/listings'
      path: '/farmer/listings'
      fullPath: '/farmer/listings'
      preLoaderRoute: typeof FarmerListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/messages': {
      id: '/farmer/messages'
      path: '/farmer/messages'
      fullPath: '/farmer/messages'
      preLoaderRoute: typeof FarmerMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/notifications': {
      id: '/farmer/notifications'
      path: '/farmer/notifications'
      fullPath: '/farmer/notifications'
      preLoaderRoute: typeof FarmerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/payments': {
      id: '/farmer/payments'
      path: '/farmer/payments'
      fullPath: '/farmer/payments'
      preLoaderRoute: typeof FarmerPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/profile': {
      id: '/farmer/profile'
      path: '/farmer/profile'
      fullPath: '/farmer/profile'
      preLoaderRoute: typeof FarmerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/reports': {
      id: '/farmer/reports'
      path: '/farmer/reports'
      fullPath: '/farmer/reports'
      preLoaderRoute: typeof FarmerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/requests': {
      id: '/farmer/requests'
      path: '/farmer/requests'
      fullPath: '/farmer/requests'
      preLoaderRoute: typeof FarmerRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/revenue': {
      id: '/farmer/revenue'
      path: '/farmer/revenue'
      fullPath: '/farmer/revenue'
      preLoaderRoute: typeof FarmerRevenueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/settings': {
      id: '/farmer/settings'
      path: '/farmer/settings'
      fullPath: '/farmer/settings'
      preLoaderRoute: typeof FarmerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/weather': {
      id: '/farmer/weather'
      path: '/farmer/weather'
      fullPath: '/farmer/weather'
      preLoaderRoute: typeof FarmerWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmercard/$slug': {
      id: '/farmercard/$slug'
      path: '/farmercard/$slug'
      fullPath: '/farmercard/$slug'
      preLoaderRoute: typeof FarmercardSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/activities': {
      id: '/tourist/activities'
      path: '/tourist/activities'
      fullPath: '/tourist/activities'
      preLoaderRoute: typeof TouristActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/booking-detail': {
      id: '/tourist/booking-detail'
      path: '/tourist/booking-detail'
      fullPath: '/tourist/booking-detail'
      preLoaderRoute: typeof TouristBookingDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/bookings': {
      id: '/tourist/bookings'
      path: '/tourist/bookings'
      fullPath: '/tourist/bookings'
      preLoaderRoute: typeof TouristBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/checklist': {
      id: '/tourist/checklist'
      path: '/tourist/checklist'
      fullPath: '/tourist/checklist'
      preLoaderRoute: typeof TouristChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/experiences': {
      id: '/tourist/experiences'
      path: '/tourist/experiences'
      fullPath: '/tourist/experiences'
      preLoaderRoute: typeof TouristExperiencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/explore': {
      id: '/tourist/explore'
      path: '/tourist/explore'
      fullPath: '/tourist/explore'
      preLoaderRoute: typeof TouristExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/help': {
      id: '/tourist/help'
      path: '/tourist/help'
      fullPath: '/tourist/help'
      preLoaderRoute: typeof TouristHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/history': {
      id: '/tourist/history'
      path: '/tourist/history'
      fullPath: '/tourist/history'
      preLoaderRoute: typeof TouristHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/home': {
      id: '/tourist/home'
      path: '/tourist/home'
      fullPath: '/tourist/home'
      preLoaderRoute: typeof TouristHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/messages': {
      id: '/tourist/messages'
      path: '/tourist/messages'
      fullPath: '/tourist/messages'
      preLoaderRoute: typeof TouristMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/nearby': {
      id: '/tourist/nearby'
      path: '/tourist/nearby'
      fullPath: '/tourist/nearby'
      preLoaderRoute: typeof TouristNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/notifications': {
      id: '/tourist/notifications'
      path: '/tourist/notifications'
      fullPath: '/tourist/notifications'
      preLoaderRoute: typeof TouristNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/payments': {
      id: '/tourist/payments'
      path: '/tourist/payments'
      fullPath: '/tourist/payments'
      preLoaderRoute: typeof TouristPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/profile': {
      id: '/tourist/profile'
      path: '/tourist/profile'
      fullPath: '/tourist/profile'
      preLoaderRoute: typeof TouristProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/reviews': {
      id: '/tourist/reviews'
      path: '/tourist/reviews'
      fullPath: '/tourist/reviews'
      preLoaderRoute: typeof TouristReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/saved-routes': {
      id: '/tourist/saved-routes'
      path: '/tourist/saved-routes'
      fullPath: '/tourist/saved-routes'
      preLoaderRoute: typeof TouristSavedRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/settings': {
      id: '/tourist/settings'
      path: '/tourist/settings'
      fullPath: '/tourist/settings'
      preLoaderRoute: typeof TouristSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/trip-planner': {
      id: '/tourist/trip-planner'
      path: '/tourist/trip-planner'
      fullPath: '/tourist/trip-planner'
      preLoaderRoute: typeof TouristTripPlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tourist/wishlist': {
      id: '/tourist/wishlist'
      path: '/tourist/wishlist'
      fullPath: '/tourist/wishlist'
      preLoaderRoute: typeof TouristWishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/listing/$id': {
      id: '/farmer/listing/$id'
      path: '/farmer/listing/$id'
      fullPath: '/farmer/listing/$id'
      preLoaderRoute: typeof FarmerListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farmer/listing/new': {
      id: '/farmer/listing/new'
      path: '/farmer/listing/new'
      fullPath: '/farmer/listing/new'
      preLoaderRoute: typeof FarmerListingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/creator/register': {
      id: '/services/creator/register'
      path: '/creator/register'
      fullPath: '/services/creator/register'
      preLoaderRoute: typeof ServicesCreatorRegisterRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/farmer/register': {
      id: '/services/farmer/register'
      path: '/farmer/register'
      fullPath: '/services/farmer/register'
      preLoaderRoute: typeof ServicesFarmerRegisterRouteImport
      parentRoute: typeof ServicesRoute
    }
  }
}

interface ServicesRouteChildren {
  ServicesCreatorRegisterRoute: typeof ServicesCreatorRegisterRoute
  ServicesFarmerRegisterRoute: typeof ServicesFarmerRegisterRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCreatorRegisterRoute: ServicesCreatorRegisterRoute,
  ServicesFarmerRegisterRoute: ServicesFarmerRegisterRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AITripPlannerRoute: AITripPlannerRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AdminActivityApprovalRoute: AdminActivityApprovalRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApprovalsRoute: AdminApprovalsRoute,
  AdminBlogsRoute: AdminBlogsRoute,
  AdminFarmApprovalRoute: AdminFarmApprovalRoute,
  AdminFraudRoute: AdminFraudRoute,
  AdminHelpRoute: AdminHelpRoute,
  AdminHomeRoute: AdminHomeRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVerifiedUsersRoute: AdminVerifiedUsersRoute,
  AdminVerifyRoute: AdminVerifyRoute,
  AuthChangePasswordRoute: AuthChangePasswordRoute,
  AuthChange_passwordRoute: AuthChange_passwordRoute,
  AuthLoginRoute: AuthLoginRoute,
  BlogIdRoute: BlogIdRoute,
  CreatorAnalyticsRoute: CreatorAnalyticsRoute,
  CreatorBoardRoute: CreatorBoardRoute,
  CreatorBookingsRoute: CreatorBookingsRoute,
  CreatorBrandDealsRoute: CreatorBrandDealsRoute,
  CreatorCollaborationsRoute: CreatorCollaborationsRoute,
  CreatorFollowersRoute: CreatorFollowersRoute,
  CreatorHelpRoute: CreatorHelpRoute,
  CreatorHomeRoute: CreatorHomeRoute,
  CreatorInstagramRoute: CreatorInstagramRoute,
  CreatorMessagesRoute: CreatorMessagesRoute,
  CreatorNotificationsRoute: CreatorNotificationsRoute,
  CreatorPaymentsRoute: CreatorPaymentsRoute,
  CreatorPortfolioRoute: CreatorPortfolioRoute,
  CreatorProfileRoute: CreatorProfileRoute,
  CreatorReportsRoute: CreatorReportsRoute,
  CreatorRevenueRoute: CreatorRevenueRoute,
  CreatorSavedFarmsRoute: CreatorSavedFarmsRoute,
  CreatorSettingsRoute: CreatorSettingsRoute,
  CreatorSocialRoute: CreatorSocialRoute,
  CreatorYoutubeRoute: CreatorYoutubeRoute,
  CreatorcardSlugRoute: CreatorcardSlugRoute,
  FarmerActivitiesRoute: FarmerActivitiesRoute,
  FarmerAddActivityRoute: FarmerAddActivityRoute,
  FarmerAnalyticsRoute: FarmerAnalyticsRoute,
  FarmerAvailabilityRoute: FarmerAvailabilityRoute,
  FarmerBoardRoute: FarmerBoardRoute,
  FarmerBookingsRoute: FarmerBookingsRoute,
  FarmerCalendarRoute: FarmerCalendarRoute,
  FarmerCollaborationsRoute: FarmerCollaborationsRoute,
  FarmerCreateFarmRoute: FarmerCreateFarmRoute,
  FarmerCreatorRequestsRoute: FarmerCreatorRequestsRoute,
  FarmerCropCalendarRoute: FarmerCropCalendarRoute,
  FarmerHelpRoute: FarmerHelpRoute,
  FarmerHistoryRoute: FarmerHistoryRoute,
  FarmerHomeRoute: FarmerHomeRoute,
  FarmerListingsRoute: FarmerListingsRoute,
  FarmerMessagesRoute: FarmerMessagesRoute,
  FarmerNotificationsRoute: FarmerNotificationsRoute,
  FarmerPaymentsRoute: FarmerPaymentsRoute,
  FarmerProfileRoute: FarmerProfileRoute,
  FarmerReportsRoute: FarmerReportsRoute,
  FarmerRequestsRoute: FarmerRequestsRoute,
  FarmerRevenueRoute: FarmerRevenueRoute,
  FarmerSettingsRoute: FarmerSettingsRoute,
  FarmerWeatherRoute: FarmerWeatherRoute,
  FarmercardSlugRoute: FarmercardSlugRoute,
  TouristActivitiesRoute: TouristActivitiesRoute,
  TouristBookingDetailRoute: TouristBookingDetailRoute,
  TouristBookingsRoute: TouristBookingsRoute,
  TouristChecklistRoute: TouristChecklistRoute,
  TouristExperiencesRoute: TouristExperiencesRoute,
  TouristExploreRoute: TouristExploreRoute,
  TouristHelpRoute: TouristHelpRoute,
  TouristHistoryRoute: TouristHistoryRoute,
  TouristHomeRoute: TouristHomeRoute,
  TouristMessagesRoute: TouristMessagesRoute,
  TouristNearbyRoute: TouristNearbyRoute,
  TouristNotificationsRoute: TouristNotificationsRoute,
  TouristPaymentsRoute: TouristPaymentsRoute,
  TouristProfileRoute: TouristProfileRoute,
  TouristReviewsRoute: TouristReviewsRoute,
  TouristSavedRoutesRoute: TouristSavedRoutesRoute,
  TouristSettingsRoute: TouristSettingsRoute,
  TouristTripPlannerRoute: TouristTripPlannerRoute,
  TouristWishlistRoute: TouristWishlistRoute,
  BlogIndexRoute: BlogIndexRoute,
  FarmerListingIdRoute: FarmerListingIdRoute,
  FarmerListingNewRoute: FarmerListingNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
